-- A credencial administrativa fixa que existia aqui foi removida.
-- Administradores devem ser criados de forma segura no Supabase e ter o código
-- rotacionado pelo painel. A migração de hardening converte credenciais antigas.
